language: go

go:
  - 1.9.x
  - 1.10.x
  - tip

go_import_path: gopkg.in/src-d/go-mysql-server.v0

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

sudo: required

install:
  - go get -v github.com/golang/dep/...
  - dep ensure
  - make dependencies

script:
  - make test-coverage
