language: go

go:
  - 1.9
  - tip

go_import_path: github.com/src-d/go-mysql-server

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

sudo: required

install:
  - make dependencies

script:
  - make test-coverage
